#
# Minigame Tokens v0.1 by RoughDragon
#
# List of Permissions:
# mgtokens.* - Gives access to all MinigameTokens commands.
# mgtokens.give - Gives access to give Tokens.
# mgtokens.set - Gives access to set Tokens.
# mgtokens.reset - Gives access to reset Tokens to 'baseTokens'.
# mgtokens.get - Gives access to see other player's tokens.
#

# The world name where Tokens are active. eg. Minigames
worldName: Minigames

# Base Tokens. Amount of Tokens Players start off with.
baseTokens: 0

# Enable Scoreboard showing Tokens.
enableScoreboard: true

# Killing Players gives Tokens.
playerKillTokens: true

# Tokens given per Kill. 'playerKillTokens' must be True.
tokensPerKill: 1
